# This docker-compose is used to run locally MongoDB.
# From the local directory of this file, run the following command on the terminal:
# $ docker-compose up

# This can be reproduce using the command line in 2 steps:
# 1) $ docker run -d --name mongoDB -p 27017:27017 --rm mongo:6.0.7 mongod --replSet rs0
# 2) $ docker exec -it mongo-set mongosh --eval "rs.initiate()"

# Below is a brief explanation of the arguments used:
# -d                  execute in detached mode.
# --name <hostname>   container name, also used as hostname.
# -p <port>:27017     container port mapping.
# --rm                for removing container at its end.
# mongo:<tag>         MongoDB image.
# 
# mongod              mongo daemon.
# --replSet <setName> define cluster name that the database will join.
# -it                 for interactive execution.
# <hostname>          container hostname on which the command will be executed.
# <cmd>               command
# --eval              built-in shell command for evaluating and executing strings as Bash command.
# "<string_cmd>"      string command.

version: "3"

services:
  mongodb:
    image: mongo:6.0.7
    container_name: mongoDB
    ports:
    - "27017:27017"
    # binding container (or service)'s name is necessary for mongo-setup service
    entrypoint: ["/usr/bin/mongod", "--bind_ip", "mongodb", "--replSet", "rsOneNode"]
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok'"]
      # equivalent to
      #test: ["CMD-SHELL", "mongosh mongo:27017/test --quiet"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
    - mongo_conf:/data/configdb
    - mongo_data:/data/db

  mongo-setup:
    image: mongo:6.0.7
    depends_on:
      mongodb:
        condition: service_healthy
    restart: "no"
    # here 'mongodb' is used for configuration
    # check rs.status().ok is useful when the container is re-run with the same volumes
    entrypoint: [ "bash", "-c", "mongosh --host mongodb:27017 --eval \"try { rs.status().ok } catch (e) { rs.initiate() }\""]
    volumes:
    - mongo_conf:/data/configdb
    - mongo_data:/data/db

volumes:
  mongo_conf:
  mongo_data: