# This workflow will build a Java project with Maven
name: Java CI with Maven and SonarCloud in Linux

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      workdir: booking-aggregator
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # SonarCloud requires at least Java 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys:  ${{ runner.os }}-m2-

    - name: Build with Maven and SonarCloud
      run: ../mvnw install -Pcoveralls -DrepoToken=$COVERALLS_REPO_TOKEN -DpullRequest=PR_NUMBER sonar:sonar -Dsonar.organization=marcopaglio-github -Dsonar.host.url=https://sonarcloud.io
      working-directory:  ${{ env.workdir }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Generate JUnit Report
      if: ${{ failure() }}
      run: ../mvnw surefire-report:report-only site:site -DgenerateReports=false -Daggregate=true
      working-directory:  ${{ env.workdir }}

    - name: Archive JUnit Report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: surefire-report-jdk-11
        path: 'booking-aggregator/target/site/'
        if-no-files-found: error
        retention-days: 30

    - name: Run Mutation Testing
      run: ../mvnw verify -Ppitest
      working-directory: ${{ env.workdir }}

    - name: Archive Pitest Report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: pitest-report-jdk-11
        path: 'booking-report/target/pit-reports/'
        if-no-files-found: error
        retention-days: 30
