# This workflow will build a Java project with Maven
name: Build with Maven in Windows

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022
    env:
      workdir: booking-aggregator
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys:  ${{ runner.os }}-m2-

    - name: Build with Maven
      run: ../mvnw.cmd install
      working-directory:  ${{ env.workdir }}

    - name: Generate JUnit Report
      if: ${{ failure() }}
      run: ../mvnw.cmd surefire-report:report-only site:site -DgenerateReports=false -Daggregate=true
      working-directory:  ${{ env.workdir }}

    - name: Archive JUnit Report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: surefire-report-jdk-11
        path: 'booking-aggregator/target/site/'
        if-no-files-found: error
        retention-days: 30