# This workflow will build a Java project with Maven
name: Java CI with Maven in MacOS

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    env:
      workdir: booking-aggregator
      java-version: 17
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK ${{ env.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ env.java-version }}

    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Build with Maven Wrapper
      id: maven-build
      run: ../mvnw install
      working-directory: ${{ env.workdir }}

    - name: Generate JUnit Report
      id: test-report
      if: ${{ failure() && steps.maven-build.conclusion != 'skipped' }}
      run: ../mvnw surefire-report:report-only surefire-report:failsafe-report-only site:site -DgenerateReports=false -Daggregate=true
      working-directory: ${{ env.workdir }}

    - name: Archive JUnit Report
      if: ${{ failure() && steps.test-report.outcome == 'success' }}
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report-jdk-${{ env.java-version }}
        path: ${{ env.workdir }}/target/site/
        if-no-files-found: error
        retention-days: 30

    - name: Archive failed GUI tests screenshots
      if: ${{ failure() && steps.maven-build.conclusion != 'skipped' }}
      uses: actions/upload-artifact@v4
      with:
        name: failed-gui-tests-screenshots
        path: '**/failed-gui-tests/'
        if-no-files-found: ignore
        retention-days: 30
