# This workflow will build a Java project with Maven
name: Java CI with Maven in MacOS

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    env:
      workdir: booking-aggregator
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Install X11 dependencies
      run: |
        brew install --cask xquartz
        export DISPLAY=:0
        xhost +

    - name: Build with Maven Wrapper
      id: maven-build
      run: ../mvnw install -Pdocker
      working-directory: ${{ env.workdir }}
