# This workflow will build a Java project with Maven
name: Java CI with Maven in Linux

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      workdir: booking-aggregator
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys:  ${{ runner.os }}-m2-

    - name: Build with Maven
      run: mvn install -Pcoveralls -DrepoToken=$COVERALLS_REPO_TOKEN -DpullRequest=PR_NUMBER
      working-directory:  ${{ env.workdir }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}

    - name: Generate JUnit Report
      if: ${{ failure() }}
      run: mvn surefire-report:report-only site:site -DgenerateReports=false -Daggregate=true
      working-directory:  ${{ env.workdir }}

    - name: Archive JUnit Report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: surefire-report-jdk-11
        path: 'booking-aggregator/target/site/'
        if-no-files-found: error
        retention-days: 30

    - name: Run Mutation Testing
      run: mvn verify -Ppitest
      working-directory: ${{ env.workdir }}

    - name: Archive Pitest Report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: pitest-report-jdk-11
        path: 'booking-report/target/pit-reports/'
        if-no-files-found: error
        retention-days: 30
