# This workflow will build a Java project with Maven
name: Java CI with Maven in MacOS

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    env:
      workdir: booking-aggregator
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install X11 dependencies
      run: |
        type -a printf
        type -a Xvfb
        type -a xvfb-run
        type -a libx11
